### ISSUE TITLE
FX move checklist

### ISSUE THREAD

**Issue by Andreya-Autumn** [surge-synthesizer/sst-effects#20]
Because why not! 

**From Surge**

- [ ] Resonator
- [x] Bonsai
- [x] Waveshaper
- [ ] Combulator
- [x] Nimbus
- [x] Treemonster
- [ ] Chorus
- [x] Flanger
- [x] Phaser
- [x] Rotary Speaker
- [x] Delay
- [x] Reverb 1
- [x] Reverb 2
- [ ] Frequency Shifter
- [ ] Ring Modulator

**From Shortcircuit**

- [x] Microgate
- [x] Bitcrusher
- [x] Phase Mod
- [x] Faux Stereo (widener)
- [x] Morph EQ
- [x] Graphic EQ
- [x] Parametric EQ
- [x] Ring Mod
- [x] Slewer

**Airwindows** 
- [ ] Galactic
- [ ] ToTape7
...and?

**Probably won't do** 
- [ ] CHOW
- [ ] Distortion
- [ ] Neuron
- [ ] Spring Reverb
- [ ] Ensemble

**useful JS with compatible licences** 
- [x] Stereo Field Manip
- [x] Floaty Delay
- [ ] Lattice Filter
- [ ] Paranoia Mangler
- [ ] Non-Linear Processor
- [ ] Amp/Cab Modeler? 
- [ ] CXF synth (as a simple oscillator maybe?)

**Comment by baconpaul** [comment]
The satin ones (chow, neuron, spring reverb, ensemble) may be tricky due to some dependencies

The wave shaper I will probably skip because we already have the shapers in a library

Nimbus I will probably skip due to extensive dependencies

Just notes to self.

**Comment by Andreya-Autumn** [comment]
Updating this list a bit. Putting some of them in a "probably not" category for the various reasons Paul named, and also because some of them we have nicer options for the same function now.

**Comment by baconpaul** [comment]
I moved freq shifter and ring mod into the 'will do' list.

**Comment by Andreya-Autumn** [comment]
Right! I forgot the surge ring mod is actually cool. :) The freq shifter my feeling was the hilbert one just sounds better so I guess we could re-implement with that and the delay instead?

**Comment by Andreya-Autumn** [comment]
I also added the JS that I find most interesting for us.

**Comment by Andreya-Autumn** [comment]
I haven't gotten any answer from Sonic Anomaly, and also realized transpire and bass professor have latency, so never mind anyway.
